/**
 * MB-SUPABASE-REPO-HYGIENE-3C — the repository must never version Supabase CLI link state.
 *
 * `supabase/.temp/` is generated by the Supabase CLI (project link + version caches). Tracked, its
 * `project-ref` / `linked-project.json` / `pooler-url` make any CLI command run from a checkout (db push,
 * migration list, db pull, ...) target a real remote project. Only git metadata is read here.
 *
 * Run: npx tsx --test src/lib/supabase-repo-hygiene.test.ts
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";

const tracked = execFileSync("git", ["ls-files", "-z"], { cwd: process.cwd(), encoding: "utf8", maxBuffer: 64 * 1024 * 1024 })
  .split("\0")
  .filter(Boolean);

const LINK_FILES = new Set(["linked-project.json", "project-ref", "pooler-url"]);

describe("Supabase CLI local state is never versioned", () => {
  it("no tracked file lives under a supabase/.temp directory", () => {
    assert.deepEqual(tracked.filter((f) => /(^|\/)supabase\/\.temp\//.test(f)), []);
  });

  it("no tracked file is a CLI project-link file", () => {
    assert.deepEqual(
      tracked.filter((f) => /(^|\/)supabase\//.test(f) && LINK_FILES.has(path.basename(f))),
      [],
    );
  });

  it(".gitignore excludes supabase/.temp/", () => {
    const rules = readFileSync(path.join(process.cwd(), ".gitignore"), "utf8").split("\n").map((l) => l.trim());
    assert.ok(rules.includes("/supabase/.temp/") || rules.includes("supabase/.temp/"));
  });

  it("no tracked supabase/ file embeds a pooler connection URL", () => {
    for (const f of tracked.filter((t) => t.startsWith("supabase/"))) {
      assert.doesNotMatch(readFileSync(path.join(process.cwd(), f), "utf8"), /pooler\.supabase\.com/, f);
    }
  });
});
